const fs = require('fs');
let code = fs.readFileSync('App.tsx', 'utf8');

code = code.replace(/filtered = filtered\.filter\(b => \(b\.name && b\.name\.toLowerCase\(\)\.includes\(query\)\) \|\| \(b\.companyName && b\.companyName\.toLowerCase\(\)\.includes\(query\)\) \|\| \(b\.email && b\.email\.toLowerCase\(\)\.includes\(query\)\) \|\| \(b\.phone && \(b\.phone\.includes\(query\) \|\| \(cleanQuery\.length > 0 && b\.phone\.replace\(\/\\D\/g, ''\)\.includes\(cleanQuery\)\)\)\)\);/g, "filtered = filtered.filter(b => (b.name && String(b.name).toLowerCase().includes(query)) || (b.companyName && String(b.companyName).toLowerCase().includes(query)) || (b.email && String(b.email).toLowerCase().includes(query)) || (b.phone && (String(b.phone).includes(query) || (cleanQuery.length > 0 && String(b.phone).replace(/\\D/g, '').includes(cleanQuery)))));");

code = code.replace(/filtered = filtered\.filter\(w => \(w\.name && w\.name\.toLowerCase\(\)\.includes\(query\)\) \|\| \(w\.companyName && w\.companyName\.toLowerCase\(\)\.includes\(query\)\) \|\| \(w\.email && w\.email\.toLowerCase\(\)\.includes\(query\)\) \|\| \(w\.phone && \(w\.phone\.includes\(query\) \|\| \(cleanQuery\.length > 0 && w\.phone\.replace\(\/\\D\/g, ''\)\.includes\(cleanQuery\)\)\)\)\);/g, "filtered = filtered.filter(w => (w.name && String(w.name).toLowerCase().includes(query)) || (w.companyName && String(w.companyName).toLowerCase().includes(query)) || (w.email && String(w.email).toLowerCase().includes(query)) || (w.phone && (String(w.phone).includes(query) || (cleanQuery.length > 0 && String(w.phone).replace(/\\D/g, '').includes(cleanQuery)))));");

code = code.replace(/filtered = filtered\.filter\(a => String\(a\.name\)\.toLowerCase\(\)\.includes\(query\) \|\| \(a\.brokerage && String\(a\.brokerage\)\.toLowerCase\(\)\.includes\(query\)\) \|\| \(a\.phone && \(a\.phone\.includes\(query\) \|\| \(cleanQuery\.length > 0 && a\.phone\.replace\(\/\\D\/g, ''\)\.includes\(cleanQuery\)\)\)\)\);/g, "filtered = filtered.filter(a => String(a.name).toLowerCase().includes(query) || (a.brokerage && String(a.brokerage).toLowerCase().includes(query)) || (a.phone && (String(a.phone).includes(query) || (cleanQuery.length > 0 && String(a.phone).replace(/\\D/g, '').includes(cleanQuery)))));");

fs.writeFileSync('App.tsx', code);
